# Generated by Django 4.1.4 on 2022-12-27 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_userreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number should be in +380xx xxx xxx xx format', regex='^\\+?3?8?0\\d{2}[- ]?(\\d[ -]?){7}$')])),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, max_length=259)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number should be in +380xx xxx xxx xx format', regex='^\\+?3?8?0\\d{2}[- ]?(\\d[ -]?){7}$')]),
        ),
    ]
